version: '3.7'

services:
    bot:
        build: https://github.com/edementyev/regbot.git
        image: regbot:latest
        command: python3 ./app/bot.py
        restart: 'no'
        networks:
            - network
        volumes:
            - ./log:/log
            - ./config:/usr/src/app/config
        depends_on:
            - db
            - redis

    db:
        image: 'postgres:alpine'
        restart: 'no'
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - network

    redis:
        image: 'redis:alpine'
        command: redis-server --appendonly yes
        restart: 'no'
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - redisdata:/data
        networks:
            - network

networks:
    network:

volumes:
    dbdata:
        name: salesboard-db
    redisdata:
        name: salesboard-redis